name: insta_food
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_responsive_framework: ^0.0.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  go_router: ^16.2.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/
    - assets/svgs/
